### ISSUE TITLE
Duplicate wicker recipes

### ISSUE THREAD

**Issue by HopsandBarley** [malcolmriley/minecraft-textiles#38]
Both recipes for wicker use sugar cane, where as the intent is for one to use flax stalks

![image](https://user-images.githubusercontent.com/78277756/131275024-a16319ac-57d6-4d6d-a5f4-0c6120597269.png)

**Comment by malcolmriley** [comment]
Thank you for the report.

Looks like I somehow botched the recipe generator cleanup [here](https://github.com/malcolmriley/minecraft-textiles/commit/a546d822bf118b25e4e6770841f430d360b7a1a9#diff-40990abddbb6f3c9ee59c1fb51331cdf105504f4ab975d85d87567a1666715ce).

This issue will be fixed in the next minor version.

**Comment by malcolmriley** [comment]
Hello again,

Given that this is a comparatively minor issue, I've decided to simply roll it into the upcoming 0.2.0 release. If all goes well, it should be out in the next few days.

**Comment by HopsandBarley** [comment]
sounds reasonable!
