### ISSUE TITLE
Raw Fiber Bales are confusing

### ISSUE THREAD

**Issue by HopsandBarley** [malcolmriley/minecraft-textiles#43]
After soaking raw fiber bales in water, they apparently change color.  but if they are submerged, you can't see that, and they are still called "Raw Fiber Bales", so you have no idea if they are ready for harvesting or not.  Would be nice if the item changed it's name once it was ready for harvesting.

![image](https://user-images.githubusercontent.com/78277756/131551972-275b571b-d968-4a83-b25e-729b58ad6624.png)

**Comment by malcolmriley** [comment]
Hello,

Thank you for the suggestion - I like the idea of changing the reported name of the bales once they are ready to harvest. I don't play with "what-am-I-looking-at" style mods myself, so this particular issue would never have occurred to me. The enhancement will be included in the upcoming 0.2.0 version.

I've toyed with the idea of some other visual indicator of "done-ness" for the fiber bales but I didn't really like the look of particles, so it's still on the drawing board for now.

**Comment by malcolmriley** [comment]
Hello again,

Your suggestion has been implemented for the upcoming 0.2.0 version by separating the Raw Fiber and Retted Fiber bales into their own blocks. Existing raw fiber bales will progress naturally into the Retted Fiber Bale block. They are also (hopefully) more visually-distinct as well.

Since Retted Fiber is its own block, it should also be easier for modpack makers (such as yourself) to add additional processing steps after retting (by modifying block drop loot tables), or to add parallel recipes using other mods.

![bales_menu](https://user-images.githubusercontent.com/28375009/131602346-045f53d2-cab4-4cd5-8008-4a9568e9ae48.png)
![bales_water](https://user-images.githubusercontent.com/28375009/131602348-3706b014-717f-4771-9ba0-47f7e6096b83.png)
