### ISSUE TITLE
1.3.3 crash? 

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [malcolmriley/minecraft-textiles#66]
ATM 7 .23 update, with Paxi, Collective, nofog, simplebackup and wily textiles 1.3.3

https://paste.ee/p/YZfF0

I broke some full grown farmers delight rice with a flint knife and crashed with an unexpected error. any ideas?

**Comment by malcolmriley** [comment]
Very strange! I don’t quite know what to make of this at a glance and I am unfortunately away from my development environment at the moment.

Does the crash happen consistently/replicably under those same conditions?

**Comment by ZephyrWindSpirit** [comment]
So I wasn't able to replicate it in single player, it was multiplayer, without having wily textiles on the server. So I've no idea why it blamed your mod. I had several crashes back to back for spamming ars spells in the twilight yesterday, and someone mentioned it was because I didn't have enough mana but whatever.

**Comment by ZephyrWindSpirit** [comment]
oops, didn't mean to do that.

**Comment by malcolmriley** [comment]
I see, thanks for looking into it.

I’m fairly certain this is a quick fix, but again, away from my dev platform at the moment so it might be a bit before I can create a build. Sorry for the inconvenience!

In the meantime, uninstalling the mod if you intend to play on a server without it should solve the problem - since the mod wouldn’t be playable in that circumstance anyways. Thanks again!

**Comment by ZephyrWindSpirit** [comment]
Another thing I had on me, unrelated maybe to this crash, was an evilcraft vengeance ring. I took that off and disabled wily textiles and so far I am running smooth. I will check the textiles crash when I get home. Had another one using ftb ultimine on a tree.

**Comment by malcolmriley** [comment]
I’m almost positive the crash is related to Wily Textiles not being present on the server but I do appreciate your investigative efforts! I’ll take a look at it once I’m back with my dev platform.

Many thanks!

**Comment by malcolmriley** [comment]
Fixed in #69 ([Commit Link](https://github.com/malcolmriley/minecraft-textiles/commit/a9c71d92452066bbda0e2dd19f42b4c1023707b9)) and will be released as public version 0.3.4.

Thanks again for your assistance!

**Comment by malcolmriley** [comment]
I see, thanks for looking into it.

I’m fairly certain this is a quick fix, but again, away from my dev platform at the moment so it might be a bit before I can create a build. Sorry for the inconvenience!

In the meantime, uninstalling the mod if you intend to play on a server without it should solve the problem - since the mod wouldn’t be playable in that circumstance anyways. Thanks again!
