### ISSUE TITLE
Found an exploit (1.18.2)

### ISSUE THREAD

**Issue by Gitcrafter** [malcolmriley/minecraft-textiles#70]
I found an exploit involving the wool/fabric+stick > fabric and fabric+dye > colored wool recipes:

when crafting a stack of wool into fabric you get a stack+16 fabric, wich when you craft it with dye you get a stack+16 colored wool, wich when crafted into fabric gets you a stack+36 colored fabric, wich are 20 fabric more then the amount you started with

**Comment by malcolmriley** [comment]
Hello,

Thank you for the report! Unfortunately I am unable to replicate the issue with only **Wily Textiles** installed. Is it possible you are using another mod that adds extra crafting recipes for dying wool items?

With **Wily Textiles** alone, crafting fabric with dye yields dyed fabric as expected (and no surplus).

**Comment by Gitcrafter** [comment]
the cause seems to be Quark´s "Can any wool color be dyed?" option, which uses the "minecraft:occludes_vibration_signals" tag to detect wool, which your fabric also has, which seems to be the cause of this

**Comment by malcolmriley** [comment]
Thank you for looking into that!

I'm sure the Quark developers have a good reason for implementing it that way, but I can't speak to what that might be. Although the base game adds all entries of `minecraft:wool` to `minecraft:occludes_vibration_signals`, since the latter tag is intended to be behavior-defining, I would think that it could (conceivably) be used for non-wool blocks. In fact, in 1.19.2 that tag is replaced with `minecraft:dampens_vibrations`, which has carpets in addition to wool.

My recommendation would be to simply disable the feature via Quark's config, and/or create a small datapack to replace the problematic recipes.

If that solution isn't satisfactory and if the Quark developers aren't able to assist, feel free to leave another message here and I'll see if I can't help figure something else out.

**Comment by Gitcrafter** [comment]
I have disabled the option now, which for me isn´t a problem, since I hardly use any wool at all

**Comment by malcolmriley** [comment]
Splendid! I'll mark this as resolved. Feel free to message back if the situation changes.
